// Copyright 2026 Matrix Origin
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
package main

const environmentHTML = `<details class="detail-panel environment-panel" id="environment" open>
<summary>运行环境与检索配置</summary>` + environmentContentHTML + `</details>`

const environmentTabHTML = `<section class="environment-panel" id="environment" aria-labelledby="environment-tab-title">
<h2 class="environment-tab-title" id="environment-tab-title">运行环境与检索配置</h2>
{{if .Environment}}` + environmentContentHTML + `{{else}}<p class="environment-note">此历史记录未自动采集环境快照。MO 版本：<code>{{.MatrixOneVersion}}</code>。</p><p class="environment-footer"><a href="report.json">完整原始记录</a></p>{{end}}</section>`

const environmentContentHTML = `<div class="environment-content" id="environment-content">
<section class="environment-section" aria-labelledby="environment-deployment"><h2 id="environment-deployment">版本与部署</h2>
<dl class="environment-summary">{{range .EnvironmentView.Summary}}<div><dt>{{.Label}}</dt><dd>{{.Value}}<small>{{.Source}}</small></dd></div>{{end}}</dl>
{{if .EnvironmentView.ClientSummary}}<p class="environment-note">压测客户端：{{.EnvironmentView.ClientSummary}}</p>{{end}}
{{if .EnvironmentView.Diagnostics.NodeNotice}}<p class="environment-node-notice" role="note">{{.EnvironmentView.Diagnostics.NodeNotice}}</p>{{end}}</section>

<section class="environment-section" aria-labelledby="environment-cache"><h2 id="environment-cache">节点与缓存</h2>
<p class="environment-note">{{.EnvironmentView.SnapshotNote}}</p>
{{if .EnvironmentView.Caches}}<div class="chart-scroll"><table class="environment-cache-table"><caption>节点存储与缓存配置（相同配置合并）</caption><thead><tr><th scope="col">节点</th><th scope="col">存储服务</th><th scope="col">后端</th><th scope="col">每节点内存缓存</th><th scope="col">每节点磁盘缓存</th><th scope="col">来源</th></tr></thead><tbody>{{range .EnvironmentView.Caches}}<tr><th scope="row">{{.Node}}</th><td>{{.Service}}</td><td>{{.Backend}}</td><td class="environment-number">{{.Memory}}</td><td class="environment-number">{{.Disk}}</td><td><small>{{.Source}}</small></td></tr>{{end}}</tbody></table></div>{{else}}<p class="environment-empty">未取得存储与缓存配置，{{if .EnvironmentView.Diagnostics.Missing}}采集原因见诊断详情{{else}}详见环境原始记录{{end}}。</p>{{end}}
{{if .EnvironmentView.MetadataCaches}}<div class="chart-scroll"><table><caption>Metadata 缓存（相同配置合并）</caption><thead><tr><th scope="col">节点</th><th scope="col">每节点容量</th><th scope="col">依据</th><th scope="col">来源</th></tr></thead><tbody>{{range .EnvironmentView.MetadataCaches}}<tr><th scope="row">{{.Label}}</th><td class="environment-number">{{.Value}}</td><td>{{.Basis}}</td><td>{{.Source}}</td></tr>{{end}}</tbody></table></div><p class="environment-note">环境默认容量按服务端系统总内存推算；运行时调整未确认。</p>{{end}}
</section>

<section class="environment-section" aria-labelledby="environment-retrieval"><h2 id="environment-retrieval">检索参数</h2>
{{if .EnvironmentView.Retrieval}}<p class="environment-note">SQL 初始会话值；测试场景可以覆盖，实际设置见场景 SQL。</p>{{range .EnvironmentView.Retrieval}}<div class="chart-scroll"><table><caption>{{.Label}}</caption><thead><tr><th scope="col">参数</th><th scope="col">值</th><th scope="col">SQL 变量</th></tr></thead><tbody>{{range .Rows}}<tr><th scope="row">{{.Label}}</th><td class="environment-number">{{.Value}}</td><td class="environment-code">{{.Source}}</td></tr>{{end}}</tbody></table></div>{{end}}{{else}}<p class="environment-empty">未取得 SQL 检索参数。</p>{{end}}</section>

<section class="environment-section" aria-labelledby="environment-monitoring"><div class="environment-heading"><h2 id="environment-monitoring">资源监控</h2><span class="environment-status">{{.EnvironmentView.MonitorStatus}}</span></div>
<p class="environment-note">{{.EnvironmentView.MonitorNote}}</p>
{{if .EnvironmentView.Monitoring}}<dl class="environment-summary">{{range .EnvironmentView.Monitoring}}<div><dt>{{.Label}}</dt><dd>{{.Value}}</dd></div>{{end}}</dl>{{end}}
{{range .ResourcePlots}}<article class="resource-plot"><h3>{{.Name}} <small>{{.Unit}} · {{.Status}}</small></h3>{{if .Error}}<p>{{.Error}}</p>{{end}}{{if .Lines}}<svg viewBox="0 0 760 195" role="img" aria-label="{{.Name}}监控时间曲线"><path d="M40 25 V155 H725" stroke="#b7c8d8" fill="none"/>{{range .Lines}}<path d="{{.Path}}" stroke="{{.Color}}" stroke-width="2.5" stroke-linecap="round" fill="none"/>{{$color := .Color}}{{range .Dots}}<circle cx="{{.X}}" cy="{{.Y}}" r="3" fill="{{$color}}"/>{{end}}{{end}}<text x="40" y="183">查询阶段开始</text><text x="575" y="183">{{printf "%.1f" .Duration}} 秒</text><text x="42" y="18">观测范围 {{printf "%.3g" .Minimum}} ～ {{printf "%.3g" .Maximum}} {{.Unit}}</text></svg><div class="chart-scroll"><table><thead><tr><th scope="col">目标</th><th scope="col">有效样本</th><th scope="col">最小 / 均值 / 最大</th></tr></thead><tbody>{{range .Lines}}<tr><th scope="row"><span style="color:{{.Color}}">●</span> {{.Label}}</th><td>{{.Samples}}</td><td>{{printf "%.3g / %.3g / %.3g" .Minimum .Mean .Maximum}}</td></tr>{{end}}</tbody></table></div>{{else}}<p class="environment-empty">暂无有效监控样本</p>{{end}}</article>{{end}}</section>

<section class="environment-section environment-evidence" aria-label="诊断与原始记录">
{{$diag := .EnvironmentView.Diagnostics}}{{if $diag.Count}}<details class="environment-details" id="environment-diagnostics"><summary>诊断详情 <small>（{{$diag.Count}} 条）</small></summary>
{{if $diag.Nodes}}<h3>节点状态</h3><div class="chart-scroll"><table><thead><tr><th scope="col">节点</th><th scope="col">采集时状态</th><th scope="col">SQL 地址</th><th scope="col">UUID</th></tr></thead><tbody>{{range $diag.Nodes}}<tr><th scope="row">{{.Label}}</th><td>{{.State}}</td><td>{{.Address}}</td><td class="environment-code">{{.ID}}</td></tr>{{end}}</tbody></table></div>{{end}}
{{if $diag.Configs}}<h3>配置差异</h3><div class="chart-scroll"><table><thead><tr><th scope="col">节点</th><th scope="col">配置</th><th scope="col">快照值</th><th scope="col">默认值</th>{{if $diag.HasFileValues}}<th scope="col">文件显式值</th>{{end}}<th scope="col">差异</th></tr></thead><tbody>{{range $diag.Configs}}<tr><td>{{.Node}}</td><th scope="row">{{.Parameter}}</th><td class="environment-value">{{.Snapshot}}</td><td class="environment-value">{{.Default}}</td>{{if $diag.HasFileValues}}<td class="environment-value">{{if eq .File "未显式设置"}}—{{else}}{{.File}}{{end}}</td>{{end}}<td>{{.Difference}}</td></tr>{{end}}</tbody></table></div>{{if $diag.HasFileValues}}<p class="environment-note">文件显式值不确认运行时已加载。</p>{{end}}{{end}}
{{if $diag.Missing}}<h3>采集缺失</h3><dl class="environment-evidence-list">{{range $diag.Missing}}<div><dt>{{.Label}}</dt><dd>{{.Value}}</dd></div>{{end}}</dl>{{end}}
</details>{{end}}
<p class="environment-footer">{{if .Environment}}<a href="environment.json">环境原始记录</a> · {{end}}<a href="report.json">完整原始记录</a></p></section>
</div>`

const environmentStyle = `
.environment-panel{--env-ink:oklch(28% .025 248);--env-muted:oklch(49% .025 248);--env-line:oklch(88% .013 248);--env-tint:oklch(97% .007 248);color:var(--env-ink)}
.environment-content{padding:2px 0 0}.environment-section{padding:24px 0;border-bottom:1px solid var(--env-line)}.environment-section:last-child{border-bottom:0;padding-bottom:0}.environment-section h2{font-size:20px;font-weight:650;margin:0 0 14px}.environment-heading{display:flex;align-items:baseline;gap:14px;flex-wrap:wrap}.environment-status{color:var(--env-muted);font-size:13px}.environment-heading h2{margin-bottom:0}
.environment-node-notice{font-size:14px;line-height:1.6;margin:18px 0 0;padding:10px 14px;border:1px solid oklch(86% .035 75);background:oklch(97% .018 75);color:var(--env-ink);overflow-wrap:anywhere}.environment-details h3{font-size:15px;font-weight:600;margin:20px 0 10px}.environment-details h3:first-of-type{margin-top:0}.environment-details>summary small{color:var(--env-muted);font-size:12px;font-weight:400}
.environment-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px 32px;margin:0}.environment-summary div{min-width:0}.environment-summary dt,.environment-evidence-list dt{color:var(--env-muted);font-size:13px}.environment-summary dd,.environment-evidence-list dd{margin:4px 0 0;overflow-wrap:anywhere}.environment-summary dd small,.environment-evidence-list dd small{display:block;color:var(--env-muted);font-size:12px;margin-top:3px}
.environment-panel table{table-layout:auto;font-size:14px}.environment-panel thead th{background:var(--env-tint);font-size:13px;font-weight:600}.environment-panel tbody th{background:transparent;font-weight:500}.environment-panel th,.environment-panel td{border-bottom:1px solid var(--env-line);vertical-align:top}.environment-panel caption{text-align:left;font-size:13px;color:var(--env-muted);padding:0 0 8px}.environment-cache-table{min-width:660px}.environment-number{font-variant-numeric:tabular-nums;white-space:nowrap}.environment-code{font:12px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere}.environment-value{min-width:110px;white-space:pre-line;overflow-wrap:anywhere}
.environment-note,.environment-empty,.environment-footer{max-width:75ch;font-size:13px;color:var(--env-muted);margin:10px 0 14px}.environment-empty{margin-bottom:0}.environment-details{padding:13px 0;border-bottom:1px solid var(--env-line)}.environment-details:last-of-type{border-bottom:0}.environment-details>summary{font-size:14px;cursor:pointer;color:var(--env-ink);font-weight:500}.environment-details>summary:focus-visible{outline:2px solid oklch(53% .12 250);outline-offset:5px;border-radius:2px}.environment-details[open]>summary{margin-bottom:16px}.environment-evidence-list{margin:0;display:grid;gap:16px}.environment-footer{margin:20px 0 0}.resource-plot{margin:24px 0;padding:0}.resource-plot svg{width:100%;height:auto;display:block;background:var(--env-tint);border:1px solid var(--env-line);border-radius:4px}.resource-plot svg text{font:12px ui-monospace,monospace;fill:#526273}.resource-plot h3 small{font-size:12px;font-weight:400}.resource-plot td{overflow-wrap:anywhere}@media(max-width:620px){.environment-summary{grid-template-columns:1fr;gap:14px}.environment-section{padding:20px 0}.environment-section h2{font-size:18px}.environment-panel th,.environment-panel td{padding:8px}.environment-content{min-width:0}.environment-evidence-list dd{font-size:14px}}
`
